### ISSUE TITLE
[feature] Add Tekton runtime as an alternative runtime options to KFP

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/pipelines#10486]
### Feature Area
The project KFP-Tekton is the place to experiment running KFP with the Tekton runtime. For KFP V1, KFP-Tekton will continue to maintain the KFP V1 capability on Tekton because it's not runtime agnostic. For KFP V2, since the backend is abstracted with backend compiler and execution client, it's easy to add a new runtime Tekton without major code changes. This issue is to track the progress of adding Tekton runtime into the Kubeflow Pipelines repo.

- [ ] 1. Update Go to 1.19 with some new golang packages https://github.com/kubeflow/pipelines/issues/10487
- New go.mod in staging branch: https://github.com/kubeflow/kfp-tekton/blob/v2-integration/go.mod
- This will include updating some minor deprecated Go code to use the new Go format.
- [ ] 2. Add the new Tekton packages into the KFP backends https://github.com/kubeflow/pipelines/issues/10488
- Most of the code are in a pluggable Tekton compiler and executor client package
- https://github.com/kubeflow/kfp-tekton/tree/v2-integration/backend/src/v2/compiler/tektoncompiler
- https://github.com/kubeflow/kfp-tekton/blob/v2-integration/backend/src/common/util/execution_client.go#L107-L127
- [ ] 3. Add the integration tests (github actions) and corresponding deployment manifests https://github.com/kubeflow/pipelines/issues/10489

### Is there a workaround currently?

---

Love this idea? Give it a 👍.

**Comment by rimolive** [comment]
Closing this issue as work is done.

/close
