### ISSUE TITLE
[Tracker] Migrate prow tests to GitHub Action

### ISSUE THREAD

**Issue by rimolive** [kubeflow/pipelines#10744]
### Description

Kubeflow Pipelines CI uses [Google's Prow infrastructure](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/kubeflow/pipelines) to run the tests for frontent and backend, as well as trigger pre and post submit tests for PRs. With the growing number of  contributors in Kubeflow Pipelines, and the limitations to troubleshoot integration tests or run locally, we propose migrate to GitHub Actions to make tests easier to run, trackable through [artifact generation](https://docs.github.com/pt/actions/using-workflows/storing-workflow-data-as-artifacts), and optionally able to run locally.

On another note, as part of CNCF graduation, we plan to use the GitHub hosted runners to make tests run faster, thus speeding up the process of PR reviews/approvals

Below is a list of the tests that needs to be migrated (we will create an issue for each test):
* [x] [Migrate periodic functional tests to GH Actions](https://github.com/kubeflow/pipelines/issues/10745)
* [ ] [Migrate presubmit tests to GH Actions](https://github.com/kubeflow/pipelines/issues/10746)
* [ ] [Migrate postsubmit tests to GH Actions](https://github.com/kubeflow/pipelines/issues/10747)

Impacted by this bug? Give it a 👍.
