### ISSUE TITLE
Tracking issue for tests that are flaky or failing when running on pushes

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/pipelines#11153]
These issues were identified in:

- https://github.com/kubeflow/pipelines/issues/11148

### Issues

- [x] https://github.com/kubeflow/pipelines/issues/10811
- [x] https://github.com/kubeflow/pipelines/issues/11156
  - [ ] https://github.com/kubeflow/pipelines/pull/11158
- [x] https://github.com/kubeflow/pipelines/issues/11160
  - [x] https://github.com/kubeflow/pipelines/pull/11162
- [x] https://github.com/kubeflow/pipelines/issues/11161
  - [x] https://github.com/kubeflow/pipelines/pull/11162
- [ ] [Issues to be created] Other failing tests in the `master` branch: https://github.com/kubeflow/pipelines/commits/
master/

### Labels

/area testing

---

Impacted by this bug? Give it a 👍.
