### ISSUE TITLE
[epic] Use images built in PRs for tests

### ISSUE THREAD

**Issue by hbelmiro** [kubeflow/pipelines#11290]
- [ ] https://github.com/kubeflow/pipelines/issues/11239#issuecomment-2405813949
  - https://github.com/kubeflow/pipelines/pull/11284
- [ ] https://github.com/kubeflow/pipelines/issues/11280
  - https://github.com/kubeflow/pipelines/pull/11281
- [ ] Fix https://github.com/kubeflow/pipelines/blob/master/scripts/deploy/github/deploy-kfp-tekton.sh to use images built in PRs (issue to be created)
- [ ] Find a better solution for using images built in PRs in deploy-kfp-tekton.sh and deploy-kfp.sh (issue to be created)

/area testing

/assign @hbelmiro @HumairAK @CarterFendley @zazulam 

---

Impacted by this bug? Give it a 👍.

**Comment by droctothorpe** [comment]
After reviewing this issue, we've decided to close it:

This is done.

If you believe this was closed in error, please feel free to reopen with additional context.
