### ISSUE TITLE
[Release] Kubeflow Pipelines 1.0.4 umbrella tracker

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#4540]
TODOs:
* [x] https://github.com/kubeflow/pipelines/issues/4539
* [x] https://github.com/kubeflow/pipelines/issues/4013#issuecomment-697302807
* [x] https://github.com/kubeflow/pipelines/issues/4531

**Comment by shaikmanu797** [comment]
@Bobgy, would you be able to include this https://github.com/kubeflow/pipelines/pull/4566 as part of 1.0.2 release? 
We need this feature for our use case to upload kubeflow pipeline versions over CI/CD.

**Comment by Bobgy** [comment]
Hi @shaikmanu797, sorry #4566 seems to depend on many changes not on `release-1.0` branch, so cherry picking it there doesn't seem like worth the effort.
We will prioritize releasing KFP 1.1 shortly after 1.0.2 release, so please wait for it.

#4577 looks easy to cherry pick. I'll include it.

**Comment by shaikmanu797** [comment]
@Bobgy just created a PR https://github.com/kubeflow/pipelines/pull/4604 to enable short options to the cli subcommands, I feel it would be handy to avoid typing length options on the cli run.

**Comment by Bobgy** [comment]
One postsubmit sample test is failing, but it's `secret` test and the problem is with the sample itself: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/kubeflow-pipeline-postsubmit-integration-test/1314828006656577536#1:build-log.txt%3A4518
rather than with KFP system.

https://github.com/kubeflow/pipelines/blob/2a1ac100a12b8f148a8bb0a61d24f56be2f035ff/samples/core/secret/secret.py#L40
We can ignore it and release.

**Comment by Bobgy** [comment]
@PatrickXYS Can you verify `1.0.3-rc.1` release?
If all good, I'm going to release `1.0.3`

**Comment by PatrickXYS** [comment]
@Bobgy Confirmed that everything works fine.

Sent PR to fix some documentation errors. #4609

**Comment by Bobgy** [comment]
All good, going to release 1.0.3

**Comment by Bobgy** [comment]
Found a problem on K8s 1.17: https://github.com/kubeflow/pipelines/issues/4627

**Comment by Bobgy** [comment]
Renaming to 1.0.4 release tracker because we need to include the cache deployer fix.

**Comment by Bobgy** [comment]
Released on GCP marketplace too
