### ISSUE TITLE
[release] 1.7.0 tracker

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#5779]
UPDATE: 1.7.0 release is out! https://github.com/kubeflow/pipelines/releases/tag/1.7.0

Code release blockers:
* [x] TFX issues
    * [x] https://github.com/kubeflow/pipelines/issues/6311
    * [x] (blockers resolved) https://github.com/kubeflow/pipelines/issues/6138
* [x] https://github.com/kubeflow/pipelines/pull/6331
* [x] https://github.com/kubeflow/pipelines/pull/6342
* [x] https://github.com/kubeflow/pipelines/issues/6252

After code release:
* [x] https://github.com/kubeflow/pipelines/issues/6350
* [ ] if argo releases 3.1.7, we should upgrade

Docs release blockers:
* [x] https://github.com/kubeflow/pipelines/issues/6306
* [ ] https://github.com/kubeflow/pipelines/issues/6310
* [x] https://github.com/kubeflow/pipelines/issues/6294#issuecomment-897340923

DONE:
* [x] https://github.com/kubeflow/pipelines/issues/6293
* [x] https://github.com/kubeflow/pipelines/issues/5689
* [x] [Mitigated] https://github.com/kubeflow/pipelines/issues/6189
* [x] https://github.com/kubeflow/pipelines/issues/6130
* [x] https://github.com/kubeflow/pipelines/issues/6053
* [x] https://github.com/kubeflow/pipelines/issues/5303#issuecomment-879565407
* [x] https://github.com/kubeflow/pipelines/issues/5954 (waiting for revert)
* [x] https://github.com/kubeflow/pipelines/issues/5943
* [x] https://github.com/tensorflow/tfx/issues/3933

After release:
* [x] manual verification of fix https://github.com/kubeflow/pipelines/issues/5717#issuecomment-852955515
* [ ] we can update reference and merge https://github.com/kubeflow/gcp-blueprints/pull/284

Prepare:
* [x] https://github.com/kubeflow/pipelines/issues/4800

**Comment by Bobgy** [comment]
Updated to 1.7.0 release, because we have big changes like upgrading MLMD store to 1.0.0

**Comment by Bobgy** [comment]
https://github.com/kubeflow/testing/commit/03c625828ac9cc13283bd226371280b0f5704c09
updated kfp-ci test cluster to 1.7.0-alpha.2 for further testing

**Comment by Bobgy** [comment]
Reports:
* [ ] kfp gcp marketplace -- support section should include github issues, instead of slack channel

**Comment by Bobgy** [comment]
mkp "use emissary executor" option tool tip is malformed, we cannot use markdown there:
![image](https://user-images.githubusercontent.com/4957653/129024060-2050ea00-55d6-456c-96a5-6ae43f1be60d.png)

**Comment by james-jwu** [comment]
FR: add v2 DSL sample to the "Getting Started" page

The sample was added as a built-in Pipeline sample. We should add it to the "Getting Started" page as well.

**Comment by Bobgy** [comment]
pipeline root parameter is called `pipeline-output-directory` in KFP UI/SDK
can we rename it to `pipeline-root` to be consistent with SDK API?

**Comment by james-jwu** [comment]
Running the sample that adds integers passes the 1st time, but fails the 2nd time:
**F0811 23:31:33.486213      15 main.go:50] Failed to execute component: failed to store output parameter value from cache: failed to parse parameter name="Output" value =15 to double: %!w(<nil>)**

https://2d99063a196f3ce0-dot-us-central1.pipelines.googleusercontent.com/#/runs/details/4de32ffc-f51f-4fc5-95d2-d084213d9f56

import kfp
import kfp.dsl as dsl
from kfp.v2.dsl import component

@component
def add(a: float, b: float) -> float:
  '''Calculates sum of two arguments'''
  return a + b

@dsl.pipeline(
  name='addition-pipeline',
  description='An example pipeline that performs addition calculations.',
#   pipeline_root='gs://my-pipeline-root/example-pipeline'
)
def add_pipeline(a: float=1, b: float=7):
  add_task = add(a, b)

from kfp import compiler
compiler.Compiler(mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE).compile(pipeline_func=add_pipeline, package_path='pipeline.yaml')

client.create_run_from_pipeline_func(
    add_pipeline,
    arguments={'a': 7, 'b': 8},
    mode=kfp.dsl.PipelineExecutionMode.V2_COMPATIBLE,
)

**Comment by Bobgy** [comment]
I think above error was fixed by https://github.com/kubeflow/pipelines/commit/2b78d16e03b1f0024389135af7f95807bb1d6354#diff-e5ea1eac6ea305b6e11fb743d381b3d9189a086e1a88ac8bf53bf64add225977L328-R330.
We just need to release KFP SDK 1.7.1 with v2 compatible.

**Comment by rui5i** [comment]
The status icon doesn't get updated until refresh the page. (Is this not supported yet or a bug?)
![Screen Shot 2021-08-11 at 4 44 20 PM](https://user-images.githubusercontent.com/31815555/129117533-913424a3-d19c-478a-b85b-629fdbac5ce2.png)

**Comment by rui5i** [comment]
labels name is a bit confusing:
pipelines.kubeflow.org/cache_enabled: 'true'
pipelines.kubeflow.org/enable_caching: 'true'

Maybe we should add a documentation for this two labels.

**Comment by capri-xiyue** [comment]
> labels name is a bit confusing:
> pipelines.kubeflow.org/cache_enabled: 'true'
> pipelines.kubeflow.org/enable_caching: 'true'
> 
> Maybe we should add a documentation for this two labels.

pipelines.kubeflow.org/cache_enabled: 'true' is for v1 and pipelines.kubeflow.org/enable_caching: 'true' is for v2 compatible and v2. We should document it somewhere

**Comment by Bobgy** [comment]
When I deploy a new AI Platform Pipelines cluster with managed storage, the v2 compatible tutorial does not work out of the box, because it's still defaulting to minio://mlpipeline bucket, but the bucket doesn't exist.

> F0811 23:48:42.309367      20 main.go:72] Failed to execute component: failed to upload output artifact "output_dataset_one" to remote storage URI "minio://mlpipeline/v2/artifacts/pipeline/[Tutorial] V2 lightweight Python components/31b88af6-8aad-45a1-aed8-58c935ea3fb5/preprocess/output_dataset_one": uploadFile(): unable to complete copying "/minio/mlpipeline/v2/artifacts/pipeline/[Tutorial] V2 lightweight Python components/31b88af6-8aad-45a1-aed8-58c935ea3fb5/preprocess/output_dataset_one" to remote storage "pipeline/[Tutorial] V2 lightweight Python components/31b88af6-8aad-45a1-aed8-58c935ea3fb5/preprocess/output_dataset_one": failed to close Writer for bucket: blob (key "pipeline/[Tutorial] V2 lightweight Python components/31b88af6-8aad-45a1-aed8-58c935ea3fb5/preprocess/output_dataset_one") (code=Unknown): AccessDenied: Access Denied.
	status code: 403, request id: 169A656A37803974, host id: 

fix: we should configure default pipeline root to GCS, when managed storage is enabled.

**Comment by Bobgy** [comment]
UI bug, for v2 compatible mode, output artifacts have URI "gcs://xxxx", but it should be "gs://xxxx", when using gcs bucket as pipeline root.

![image](https://user-images.githubusercontent.com/4957653/129118141-73d5359b-e8d2-41ce-a6a6-e1eb8363ca26.png)

**Comment by james-jwu** [comment]
Compiling the Vertex Pipeline sample produced an error:
...
/opt/conda/lib/python3.7/site-packages/kfp/compiler/v2_compat.py in update_op(op, pipeline_name, pipeline_root, launcher_image)
    127       k8s_client.V1EnvFromSource(config_map_ref=config_map_ref))
    128 
--> 129   op.arguments = list(op.container_spec.command) + list(op.container_spec.args)
    130 
    131   runtime_info = {

AttributeError: 'NoneType' object has no attribute 'command'

**Comment by capri-xiyue** [comment]
How should cache work when everything is same except the pipeline_root?

**Comment by Bobgy** [comment]
Fix postsubmit tests: https://github.com/kubeflow/pipelines/commits/master

**Comment by Bobgy** [comment]
We need documentation for pipeline root

**Comment by Bobgy** [comment]
@rui5i yes, that's expected behavior for now.
cc @zijianjoy to consider as a FR.

https://github.com/kubeflow/pipelines/issues/5779#issuecomment-897233672

**Comment by zijianjoy** [comment]
> @rui5i yes, that's expected behavior for now.
> cc @zijianjoy to consider as a FR.
> 
> [#5779 (comment)](https://github.com/kubeflow/pipelines/issues/5779#issuecomment-897233672)

@Bobgy @rui5i Sounds good, created https://github.com/kubeflow/pipelines/issues/6317 to track this issue.

**Comment by zijianjoy** [comment]
I got the following errors when I run the following samples using KFP backend 1.7.0-rc.3 and SDK 1.7.0.

```
python3 -m samples.test.metrics_visualization_v2_test
python3 -m samples.test.metrics_visualization_v1_test
```

The error I got:

![viserror](https://user-images.githubusercontent.com/37026441/129264086-1f130b9f-74b5-457c-9270-a5751521f562.png)

**Comment by Bobgy** [comment]
Until this comment, every open issue has been added to https://github.com/kubeflow/pipelines/projects/13#column-14866979.

**Comment by zijianjoy** [comment]
Hello  @chensun , should we export HTML and Markdown in https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/v2/dsl/__init__.py#L23? I am not able to use them when building visualization pipeline.

**Comment by zijianjoy** [comment]
All visualization in v2 syntax is not available, need some debugging to figure out the root cause.
![visualizationempty](https://user-images.githubusercontent.com/37026441/129405690-0e935909-25da-41a7-9690-652596104912.png)

**Comment by Bobgy** [comment]
@zijianjoy visualization testing has always been an area of headache, because it needs to be done manually. I think it's possible to automate this by building an e2e test that
1. run the visualization pipeline, returns a URI to the run details page
2. run a UI e2e test (maybe use cypress) that goes to the run details page, click the node and visualization tab, verify the visualization tab content.

This can remove the need for manual testing.

Recording this idea for reference, we can continue to observe how often it breaks.

**Comment by Bobgy** [comment]
1.7.0 on Google Cloud Marketplace also released!
