### ISSUE TITLE
[release] 1.8.0 tracker

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6015]
TODOs:
* [x] https://github.com/kubeflow/pipelines/issues/7148
* [x] #6014 
* [x] #6987 
* [x] change emissary executor to default
* [x] MLMD upgrade to v1.5.0
* [x] Argo upgrade to v3.2.3

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by zijianjoy** [comment]
We have completed the last item: switch to Emissary executor by default: https://www.kubeflow.org/docs/components/pipelines/installation/choose-executor/#docker-executor
