### ISSUE TITLE
v2 compatible mode -- known caveats & breaking changes

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/pipelines#6133]
This issue is a living tracker for known caveats & breaking changes of v2 compatible mode to facilitate visibility:
The information is updated as KFP 1.7.0

Breaking changes:
* https://www.kubeflow.org/docs/components/pipelines/sdk/v2/v2-compatibility/#building-pipelines-using-the-kubeflow-pipelines-sdk-v2
* `command` must be specified in [Kubeflow Pipelines component specification](https://www.kubeflow.org/docs/components/pipelines/reference/component-spec/).
* https://github.com/kubeflow/pipelines/issues/5834 
* https://github.com/kubeflow/pipelines/issues/5711
* v2 compatible mode will require KFP backend 1.7.0+, but v1 mode does not have any prerequisites on KFP backend version.

Known caveats:
* [ ] Pipelines do not run on [the full Kubeflow] distributions with Multi-User Kubeflow Pipelines. [#5680]
* [ ] https://github.com/kubeflow/pipelines/issues/5831
* [ ] https://github.com/kubeflow/pipelines/issues/5673
* [ ] https://github.com/kubeflow/pipelines/issues/6132
* [ ] https://github.com/kubeflow/pipelines/issues/5835
* [ ] v2 compatible mode and v1 mode have different perf / scalability characteristics, which we haven't verified in large scale.
* [ ] Because there aren't enough usage, it's very likely there are more changes we haven't found/thought of.
* [ ] When consuming an input artifact by URI, its file content is still downloaded to the container regardless. [#5671]
* [ ] https://github.com/kubeflow/pipelines/issues/6429

Fixed caveats:
* [ ] https://github.com/kubeflow/pipelines/issues/6293
* [x] Pipelines using [v1 mlpipeline-ui-metadata visualization](/docs/components/pipelines/sdk/output-viewer/) do not compile. [#5666]
* [x] UI integration is implemented.
* [x] Caching is work-in-progress. [#5667]

[the full Kubeflow]: /docs/components/pipelines/installation/overview/#full-kubeflow
[#5680]: https://github.com/kubeflow/pipelines/issues/5680
[#5666]: https://github.com/kubeflow/pipelines/issues/5666
[#5671]: https://github.com/kubeflow/pipelines/issues/5671
[#5667]: https://github.com/kubeflow/pipelines/issues/5667

**Comment by Bobgy** [comment]
Closing because v2 compatible is no longer supported, we are working on the complete KFP v2.

/cc @chensun 
We used to have this issue for v2 compatible, a lot of them are still unsolved for v2 engine mode as well.
