### ISSUE TITLE
v2 UI tracker

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#6198]
* POC and Design
   * [x] https://github.com/kubeflow/pipelines/issues/6073
   * [x] #6126
   * [x] #6301

* proto
  * [x] #6205
  * [x] #6215
  * [x] #6272
  * [x] #7611
  * [x] #7444

* Mock backend
   * [x] #6212
   * [x] #6232
   * [x] #6302
   * [x] Create pipelineSpec sample tests

* Static Pipeline Graph
  * [x] #6778
  * [x] #6270
  * [x] #6280
  * [x] #6397
  * [x] #6419
  * [x] #6398
  * [x] #6758

* Pipeline List Page
  * [x] Render pipeline name, pipeline ID, source code, description, upload time.
  * [x] Render pipeline versions in a paginated dropdown.

* Upload Pipeline or Pipeline Version Page (pending backend+API implementation)
  * [x] #6672

* Pipeline Detail Page
  * [x] #6179
  * [x] #6214
  * [x] #6303
  * [x] Use pipeline ID to determine specific pipeline template
  * [x] Use pipeline ID + version to determine specific pipeline template
  * [x] Compile PipelineSpec proto to javascript class.
  * [x] Retrieve pipeline spec payload from backend, and convert to jspb object.
  * [x] Convert IR to DAG understandable by ReactFlow
  * [x] #6633
  * [x] #6399
  * [x] #6610
  * [x] #6611
  * [x] #6279
  * [x] #6779

* Run List Page
  * [x] #6400
  * [x] #6780

  
* New Run Page
  * [x] #7598
  * [x] #7599
  * [x] #7600
  * [x] Support creating new run 
  * [x] Support creating new recurring run.
  * [x] Support Pipeline upload in standalone mode and multi-user mode (namespaced).
  * [x] Upload V2 pipeline in project selector of New Run page.

* Runtime Pipeline Graph
  * [x] #6686
  * [x] Read Context from MLMD store
  * [x] Read Execution from MLMD store
  * [x] Read Artifact from MLMD store
  * [x] #6673
  * [x] Define runtime status css styling for Execution, Artifact, sub-DAG. (need UX help) 
  * [x] #6674
  * [x] Convert from MLMD and pipeline template to Stateful DAG when loading runtime DAG.

* Run Detail Page
  * [x] #6675
  * [x] #6708
  * [x] #6710
  * [x] #6707
  * [x] #6676
    * [x] #6739
    * [x] #6740
    * Side panel: sub-DAG: sub-DAG detail, Input/Output
  * [x] Go from Execution detail page to Run Detail page with execution node selected.

* MLMD
  * [x] #6436
  * [x] #6915

* UX
  * [x] Need UX work for all DAG UI components.
  * [x] #6283

* Others
  * [x] #6264
  * [x] #7379
  * [x] https://github.com/kubeflow/pipelines/issues/6912
  * [x] #7610

### Post-Alpha

* Static Pipeline Graph
  * Define static status css styling for Ranking algorithm. 

* Run List Page
  * https://github.com/kubeflow/pipelines/issues/6912
  * https://github.com/kubeflow/pipelines/issues/6132
  
* Run Detail Page
  * Shows Run output: all metrics https://github.com/kubeflow/pipelines/issues/7339
  * Shows Run output: all pipeline level output artifacts
  * Shows Parameters, pipeline definition link in Detail tab

* Mock backend
   * Mock get Metadata response (needs breakdown)

* Side Panel for KFPv2 Run 
  * Execution
    * Volume
    * Logs
    * Pod
    * Events
    * Task Details
      *  #6732

* Run comparison page
  * [x] #7756
  * [x] #7840
  * [x] #7841
  * [x] #7842
 
* Others
  * Consider Using [StoryShots and Puppeteer](https://github.com/storybookjs/storybook/tree/master/addons/storyshots/storyshots-puppeteer) for Visual testing. 
  * Support exitHandler scenario 
  * Multi-layer lineage graph using MLMD 1.4 https://github.com/google/ml-metadata/releases/tag/v1.4.0
  * https://github.com/kubeflow/pipelines/issues/6374
  * Add post-submit test for KFPv2
  * Compare run: https://github.com/kubeflow/pipelines/issues/7476
