### ISSUE TITLE
[release] Backend 1.8.0 tracker

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#7263]
## Cherry pick PRs

Make sure to cherry pick the following PRs to `release-1.8` branch before making the official release:

- [x] https://github.com/kubeflow/pipelines/pull/7252
- [x] https://github.com/kubeflow/pipelines/pull/7267
- [x] https://github.com/kubeflow/pipelines/pull/7227
- [x] https://github.com/kubeflow/pipelines/pull/7273
- [x] https://github.com/kubeflow/pipelines/pull/7155
- [x] https://github.com/kubeflow/pipelines/pull/7311

Validate the new release candidate before official release.

## Instruction

https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#release-manager-instructions (Note, we need to skip some steps)

**Comment by zijianjoy** [comment]
One more item to cherry pick: https://github.com/kubeflow/pipelines/pull/7227

**Comment by zijianjoy** [comment]
Hello Chen, would you mind also picking up this PR? https://github.com/kubeflow/pipelines/pull/7155

**Comment by chensun** [comment]
Released: https://github.com/kubeflow/pipelines/releases/tag/1.8.0
