### ISSUE TITLE
Pipelines WG Roadmap for KF 1.7 

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#8411]
This is for tracking the progress for KFP deliverables in Kubeflow 1.7:

- [ ]  Enter KFP v2 beta phase
  - [ ] Introduce KFP APIv2 package which is a new standard for communicating with KFP server.
  - [ ] Complete Sub-DAG visualization on KFPv2 UI.
  - [ ] [KFPv2 Documentation](https://www.kubeflow.org/docs/components/pipelines/v2/)
  - [ ] [Tentative] Status IR in Backend Run API.
- [ ]  SDK
  - [ ] Support parallelism setting in ParallelFor 
  - [ ] Support Pipeline as a component and exit handler.
  - [ ] Support [dynamic importer metadata](https://github.com/kubeflow/pipelines/pull/7660)
  - [ ] Authoring Pipelines with a list of artifacts.
  - [ ] Support for parallel-for fan-in.
  - [ ] Multiple Condition fan-in.

**Comment by zijianjoy** [comment]
cc @jbottum @chensun @james-jwu
