### ISSUE TITLE
Tracking: PostgreSQL support in KFP

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/pipelines#9813]
PostgreSQL request has become the top upvoted issue on KFP repo: https://github.com/kubeflow/pipelines/issues/7512. This issue is for tracking the work of this integration.

- [ ] KFP Backend integration
  - [x] Define the DB config for PostgreSQL DB info
    - [x] Basic connection config
    - [ ] Secure connection config: passfile, hostaddr, ssl mode, certificate, etc.
    - [x] Flag to switch between Postgresql driver and MySQL driver
  - [x] ~~#9859~~
  - [ ] Syntax support of PostgreSQL DB in backend
    - [ ] Adopt a different syntax during initialization. (schema difference)
    - [ ] Adopt a different syntax during execution. (Modification of data)
    - [ ] Explore the dialect difference and develop a control mechanism to enable easy testing on the storage layer. 
  - [ ] Testing
    - [ ] Unit testing for Postgresql behavior.
    - [ ] Functional testing for Postgresql behavior.
    - [ ] E2E testing for Postgresql behavior.
  - [ ] Cache server integration
  - [ ] KFP API server integration
  - [ ] Manifest support for Postgresql
    - [x] #9860
    - [x] #9861
    - [ ] Marketplace KFP (managed CloudSQL instance)

- [ ] MLMD integration
  - [ ] Develop Postgresql integration on MLMD
    - [ ] Investigate https://github.com/google/ml-metadata/issues/194#issuecomment-1975207465
  - [ ] Release new version of MLMD
  - [x] #9848
  - [ ] Manifest support for Postgresql in MLMD
    - [ ] Standalone KFP
    - [ ] Full Kubeflow Kubeflow
    - [ ] Marketplace KFP (managed CloudSQL instance)

**Comment by zijianjoy** [comment]
cc @chensun

**Comment by EshaanAgg** [comment]
Hi! I am Eshaan Aggarwal, an avid Open Source enthusiast from India. I am a web developer proficient in GoLang and PostgreSQL and have recently started learning about Kubernetes. I would love to contribute to this issue and hopefully join Kubeflow as a GSoC '24 mentee. Are there any pre-tests or other beginner-friendly contributions I can make to get acquainted with this project and as a proof of skill?

**Comment by UditNayak** [comment]
Hello, I'm Udit. Proficient in Python, Golang, and PostgreSQL, I've recently completed a comprehensive course on Kubernetes. The skills acquired perfectly align with the requirements of this project, making it an ideal platform for me to apply and further enhance my knowledge. I'm enthusiastic about contributing to this GSoC project, especially on the specified issue. Eagerly anticipating the chance to contribute to its development!

**Comment by zijianjoy** [comment]
Hello @EshaanAgg and @UditNayak , thank you for your interest and I am assuming @rimolive will be your mentor. 

As a start, I would recommend learning:
- PostgreSQL syntax
- GORM which is a database syntax abstraction library: https://gorm.io/index.html
- Have a kubernetes environment yourself for development.

Then, my advice to the development will be in following orders:
1. Make sure you can bring up KFP in the kubernetes environment
2. Make sure you can bring up a postgresql instance and access to it manually in the kubernetes environment
3. Make changes in KFP API server so it can read postgresql connection config from parameter/envionrment-variable. Then KFP API server should establish connection with the postgresql instance in the same cluster with such connection config.
4. Make corresponding GORM change so that CRUD (create/read/update/delete) operation of KFP can be executed correctly using postgresql. (It is a good time to write some unit test or E2E test)
5. Perform the similar actions as above for cache server.

I believe @rimolive can facilitate more once you dive deep into the project. But feel free to take any task you want to work on and ask questions along the way.

**Comment by rimolive** [comment]
In addition to what @zijianjoy said, please join us on our Slack. We have the #gsoc-participants channel to welcome everyone interested in the GSoC projects.

**Comment by Irshu786** [comment]
@zijianjoy Im currently doing ops in kubeflow, loved the concept of changing db, Will be working on these. 

#Make sure you can bring up KFP in the kubernetes environment
#Make sure you can bring up a postgresql instance and access to it manually in the kubernetes environment
#Make changes in KFP API server so it can read postgresql connection config from parameter/envionrment-variable. Then KFP API #server should establish connection with the postgresql instance in the same cluster with such connection config.
#Make corresponding GORM change so that CRUD (create/read/update/delete) operation of KFP can be executed correctly using postgresql. (It is a good time to write some unit test or E2E test)
#Perform the similar actions as above for cache server.

**Comment by SnehaAgg0212** [comment]
@zijianjoy I am a BE developer from India and am comfortable with python, goLang, java, Kubernetes and SQL databases. I would like to contribute to this issue. What are the steps?

**Comment by jiduyuting** [comment]
hello@zijianjoy I'm a junior studen from China major in  computer science and technology, I'm very interested in open source project and want to do some contribution to this project, at the same time to improve my skill. I have joined our school lab which connect with database and cloud. So I frequently contact with postgresql and kubernetes. I'm doing the steps you refered above,but I can't join in the #gsoc-participants,can this have influence?

**Comment by Irshu786** [comment]
Hey Guys,

Everyone has setup local kubeflow setup ?

**Comment by sagnik3788** [comment]
@zijianjoy anyone working on this issue ?

**Comment by rimolive** [comment]
@sagnik3788 This is part of the Google Summer of Code. You can find details in https://www.kubeflow.org/events/gsoc-2024/#project-9-postgresql-integration-in-kubeflow-pipelines.

**Comment by DajunZhou** [comment]
When will official support for PostgreSQL be available?

**Comment by DajunZhou** [comment]
Hi Kubeflow team and community,

I’ve been following this issue closely since our company, due to internal policies, cannot use MySQL, and we’re really looking forward to full PostgreSQL support in Kubeflow Pipelines. The flexibility of PostgreSQL would be a major advantage for us in deploying and managing our ML workflows.

Could the maintainers provide an update on the timeline or roadmap for officially supporting PostgreSQL? We’d love to know when we might expect this integration to be fully implemented.

Thanks for all the great work on this project!

Best regards

**Comment by arjun-thekkethil** [comment]
Hi @rimolive  @shivaylamba,

I'm Arjun T, a B.Tech student and aspiring contributor. I'm interested in working on this issue as part of Google Summer of Code 2025, and I'd love to help implement PostgreSQL support for Kubeflow Pipelines.

I've started exploring the codebase and familiarizing myself with the backend components. I’d appreciate any guidance on the current status of this feature, and whether there are any existing design documents or initial tasks that I can take up to start contributing effectively.

Looking forward to your suggestions and happy to collaborate!

Best regards,  
Arjun T

**Comment by boydfd** [comment]
Hi Kubeflow team @rimolive @zijianjoy,

Due to the requirements of a previous project, I helped investigate the possibility of adapting Kubeflow Pipelines for PostgreSQL compatibility. Through some code modifications, I successfully integrated PostgreSQL locally and was able to run the project's demo pipeline smoothly without encountering any obvious errors.

However, I might have introduced some breaking changes that could potentially cause issues with MySQL functionality (which I haven't had time to test). Therefore, I'd like to publish this code and see if anyone has the time to help integrate these changes properly and perform thorough testing.

Anyone interested can refer to this commit: https://github.com/boydfd/pipelines/commit/bb6fb6bd4f86f9dea6f3345fc7506e9adca61b4b

Here's a summary of the key modifications:

1. Cache Server:
  - Added PostgreSQL configuration and database initialization code.
  - Modified the ID field generation to support PostgreSQL (as it lacks the AUTO_INCREMENT feature found in MySQL).
2. Backend:
  - Modified PostgreSQL database initialization code.
  - Model: All database field names in the models were changed to lowercase. This is because PostgreSQL defaults identifiers to lowercase unless they are enclosed in double quotes.
  - Storage:
    - Replaced all instances of sq.select/sq.insert with s.db.GetStatementBuilder().select/s.db.GetStatementBuilder().insert. This change was necessary because PostgreSQL uses numbered placeholders ($1, $2, etc.) instead of the question mark (?) used by the previous library/MySQL.
    - Adjusted some queries in the job storage and run storage components to be compatible with ONLY_FULL_GROUP_BY behavior. PostgreSQL's aggregate functions require that all selected columns are either aggregated or included in the GROUP BY clause.
    - Implemented a PostgreSQL-specific version of SQLDialect and added corresponding tests.

The images below provide some evidence from my local testing.

![Image](https://github.com/user-attachments/assets/e8a63329-34d0-40de-b123-78343efbdb84)

![Image](https://github.com/user-attachments/assets/0d9ba81f-0cd9-45dc-a474-be57dc86a1c5)

![Image](https://github.com/user-attachments/assets/db55adba-c74a-448b-bb78-91130063565e)

![Image](https://github.com/user-attachments/assets/ec0a5267-e5c9-4bf8-b6ef-32f6a3b308f6)

Hope PostgreSQL support can be officially integrated soon.

**Comment by nickalexander-disco** [comment]
Hi Everyone, I have modified the source to include full Postgres support. I have modified the code so it no longer uses Squirrel and SQL generator but uses native GORM through out. All test cases are passing and would like to contribute this source to the project. Through the use of native GORM should also be easier to add support for other databases if required. Currently inline with master branch.
